language: python
matrix:
  include:
    - python: "2.7"
      env: TOXENV=py27
    - python: "2.7"
      env: TOXENV=docs

virtualenv:
  system_site_packages: true

sudo: required
dist: trusty

env:
  global:
    - PG_CONFIG=/usr/lib/postgresql/9.3/bin/pg_config

addons:
  postgresql: "9.3"
  apt:
    packages:
    - postgresql-server-dev-9.3
    - pandoc

services:
- postgresql

before_install:
  - git clone --recursive https://github.com/timstaley/voeventdb servercode
  - cd servercode/external/q3c
  - pg_config --version
  - make
  - sudo make install
  - psql -c "\du" -U postgres | cat
  - psql -l | cat
  - psql -c "create database $USER;" -U postgres | cat
  - pip install --upgrade pip virtualenv
install:
  - cd ${TRAVIS_BUILD_DIR}
  - pip install tox
  - pip freeze
script:
  - cd ${TRAVIS_BUILD_DIR}
  - tox -v

