sudo: required

addons:
  postgresql: "9.5"
  apt:
    packages:
    - postgresql-server-dev-9.5
    - pandoc

services:
- postgresql

language: python

matrix:
  include:
    - python: "2.7"
      env: TOXENV=py27
    - python: "3.4"
      env: TOXENV=py34
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.6"
      env: TOXENV=docs3


before_install:
    # Pre-cache long-builds before we go into tox, avoids 'no-stdout' timeouts.
  - pip install lxml numpy
  - git clone --recursive https://github.com/timstaley/voeventdb servercode
  - cd servercode/external/q3c
  - pg_config --version
  - make
  - sudo make install
  - psql -c "\du" -U postgres | cat
  - psql -l | cat
  - psql -c "create database $USER;" -U postgres | cat
  - pip install --upgrade pip virtualenv
  - pip install codecov
install:
  - cd ${TRAVIS_BUILD_DIR}
  - pip install tox
  - pip freeze
script:
  - cd ${TRAVIS_BUILD_DIR}
  - tox --showconfig
  - tox -v
after_success:
  - tox -e coverage-report
  - codecov

notifications:
  email:
    on_success: never
    on_failure: always

